version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - ./data/db/:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret123root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: 12345wordpress54321

  wordpress:
    depends_on:
      - db
    image: wordpress:php7.1
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: 12345wordpress54321
      LETSENCRYPT_HOST: wordpress.example.org
      LETSENCRYPT_EMAIL: ihremail@example.org
      VIRTUAL_HOST: wordpress.example.org
      VIRTUAL_PORT: 80

    working_dir: /var/www/html
    volumes:
      - ./data/wordpress:/var/www/html/wp-content
 
  portainer:
    image: portainer/portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/portainer:/data

  watchtower:
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30      

  nginxproxy:
    image: jwilder/nginx-proxy
    restart: unless-stopped
    volumes:
     - ./data/certs:/etc/nginx/certs
     - ./conf:/etc/nginx/conf.d
     - ./dhparam:/etc/nginx/dhparam
     - ./data/vhosts:/etc/nginx/vhost.d
     - ./data/html:/usr/share/nginx/html
     - /var/run/docker.sock:/tmp/docker.sock
    ports:
     - 80:80
     - 443:443
    labels:
     - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"

  nginxproxy_comp:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: unless-stopped
    depends_on:
     - nginxproxy
    volumes:
     - ./data/certs:/etc/nginx/certs:rw
     - ./conf:/etc/nginx/conf.d
     - ./dhparam:/etc/nginx/dhparam
     - ./data/vhosts:/etc/nginx/vhost.d
     - ./data/html:/usr/share/nginx/html
     - /var/run/docker.sock:/var/run/docker.sock:ro


